services:
  web:
    image: asistenmu:1.0.0
    container_name: serv-asistenmu
    command: ["sh", "-c", "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8080"]
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8080:8080"
